/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author COMPAQ
 */
public class Iniciar extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar
     */
    public Iniciar() {
        initComponents();
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScoresA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewGame = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GameN = new javax.swing.JLabel();
        ScoresN = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoresA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ScoreA.png"))); // NOI18N
        ScoresA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ScoresAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScoresAMouseExited(evt);
            }
        });
        jPanel1.add(ScoresA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));
        ScoresA.getAccessibleContext().setAccessibleName("Score");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/rey.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("Rey");

        NewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/NewGameA.png"))); // NOI18N
        NewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewGameMouseExited(evt);
            }
        });
        jPanel1.add(NewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("GreedyKing...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        GameN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/NewGameN.png"))); // NOI18N
        GameN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GameNMouseClicked(evt);
            }
        });
        jPanel1.add(GameN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        ScoresN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ScoreN.png"))); // NOI18N
        ScoresN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScoresNMouseClicked(evt);
            }
        });
        jPanel1.add(ScoresN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewGameMouseEntered
this.NewGame.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_NewGameMouseEntered

    private void NewGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewGameMouseExited
this.NewGame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_NewGameMouseExited

    private void GameNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GameNMouseClicked
this.dispose();
NickName n=new NickName();
n.show();
// TODO add your handling code here:
    }//GEN-LAST:event_GameNMouseClicked

    private void ScoresNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoresNMouseClicked
this.dispose();
Scores s=new Scores();
s.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_ScoresNMouseClicked

    private void ScoresAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoresAMouseEntered
this.ScoresA.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ScoresAMouseEntered

    private void ScoresAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoresAMouseExited
this.ScoresA.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ScoresAMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameN;
    private javax.swing.JLabel NewGame;
    private javax.swing.JLabel ScoresA;
    private javax.swing.JLabel ScoresN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
